export const translations = {
	data: [
		{ node_id: 'n1', en: 'Hello', es: 'Hola' },
		{ node_id: 'n2', en: 'Good morning', es: 'Buenos días' },
		{ node_id: 'n3', en: 'Good afternoon', es: 'Buenas tardes' },
		{ node_id: 'n4', en: 'Good evening', es: 'Buenas noches' },
		{ node_id: 'n5', en: 'Goodbye', es: 'Adiós' },
		{ node_id: 'n6', en: 'Please', es: 'Por favor' },
		{ node_id: 'n7', en: 'Thank you', es: 'Gracias' },
		{ node_id: 'n8', en: "You're welcome", es: 'De nada' },
		{ node_id: 'n9', en: 'Excuse me', es: 'Disculpe' },
		{ node_id: 'n10', en: "I'm sorry", es: 'Lo siento' },
		{ node_id: 'n11', en: 'One', es: 'Uno' },
		{ node_id: 'n12', en: 'Two', es: 'Dos' },
		{ node_id: 'n13', en: 'Three', es: 'Tres' },
		{ node_id: 'n14', en: 'Four', es: 'Cuatro' },
		{ node_id: 'n15', en: 'Five', es: 'Cinco' },
		{ node_id: 'n16', en: 'Six', es: 'Seis' },
		{ node_id: 'n17', en: 'Seven', es: 'Siete' },
		{ node_id: 'n18', en: 'Eight', es: 'Ocho' },
		{ node_id: 'n19', en: 'Nine', es: 'Nueve' },
		{ node_id: 'n20', en: 'Ten', es: 'Diez' },
		{ node_id: 'n21', en: 'Eleven', es: 'Once' },
		{ node_id: 'n22', en: 'Twelve', es: 'Doce' },
		{ node_id: 'n23', en: 'Thirteen', es: 'Trece' },
		{ node_id: 'n24', en: 'Fourteen', es: 'Catorce' },
		{ node_id: 'n25', en: 'Fifteen', es: 'Quince' },
		{ node_id: 'n26', en: 'Sixteen', es: 'Dieciséis' },
		{ node_id: 'n27', en: 'Seventeen', es: 'Diecisiete' },
		{ node_id: 'n28', en: 'Eighteen', es: 'Dieciocho' },
		{ node_id: 'n29', en: 'Nineteen', es: 'Diecinueve' },
		{ node_id: 'n30', en: 'Twenty', es: 'Veinte' },
		{ node_id: 'n31', en: 'Thirty', es: 'Treinta' },
		{ node_id: 'n32', en: 'Forty', es: 'Cuarenta' },
		{ node_id: 'n33', en: 'Fifty', es: 'Cincuenta' },
		{ node_id: 'n34', en: 'Sixty', es: 'Sesenta' },
		{ node_id: 'n35', en: 'Seventy', es: 'Setenta' },
		{ node_id: 'n36', en: 'Eighty', es: 'Ochenta' },
		{ node_id: 'n37', en: 'Ninety', es: 'Noventa' },
		{ node_id: 'n38', en: 'One hundred', es: 'Cien' },
		{ node_id: 'n39', en: 'Monday', es: 'Lunes' },
		{ node_id: 'n40', en: 'Tuesday', es: 'Martes' },
		{ node_id: 'n41', en: 'Wednesday', es: 'Miércoles' },
		{ node_id: 'n42', en: 'Thursday', es: 'Jueves' },
		{ node_id: 'n43', en: 'Friday', es: 'Viernes' },
		{ node_id: 'n44', en: 'Saturday', es: 'Sábado' },
		{ node_id: 'n45', en: 'Sunday', es: 'Domingo' },
		{ node_id: 'n46', en: 'January', es: 'Enero' },
		{ node_id: 'n47', en: 'February', es: 'Febrero' },
		{ node_id: 'n48', en: 'March', es: 'Marzo' },
		{ node_id: 'n49', en: 'April', es: 'Abril' },
		{ node_id: 'n50', en: 'May', es: 'Mayo' },
		{ node_id: 'n51', en: 'June', es: 'Junio' },
		{ node_id: 'n52', en: 'July', es: 'Julio' },
		{ node_id: 'n53', en: 'August', es: 'Agosto' },
		{ node_id: 'n54', en: 'September', es: 'Septiembre' },
		{ node_id: 'n55', en: 'October', es: 'Octubre' },
		{ node_id: 'n56', en: 'November', es: 'Noviembre' },
		{ node_id: 'n57', en: 'December', es: 'Diciembre' },
		{ node_id: 'n58', en: 'Red', es: 'Rojo' },
		{ node_id: 'n59', en: 'Blue', es: 'Azul' },
		{ node_id: 'n60', en: 'Green', es: 'Verde' },
		{ node_id: 'n61', en: 'Yellow', es: 'Amarillo' },
		{ node_id: 'n62', en: 'Black', es: 'Negro' },
		{ node_id: 'n63', en: 'White', es: 'Blanco' },
		{ node_id: 'n64', en: 'Orange', es: 'Naranja' },
		{ node_id: 'n65', en: 'Purple', es: 'Morado' },
		{ node_id: 'n66', en: 'Pink', es: 'Rosa' },
		{ node_id: 'n67', en: 'Brown', es: 'Marrón' },
		{ node_id: 'n68', en: 'Gray', es: 'Gris' },
		{ node_id: 'n69', en: 'To be', es: 'Ser/Estar' },
		{ node_id: 'n70', en: 'To have', es: 'Tener' },
		{ node_id: 'n71', en: 'To go', es: 'Ir' },
		{ node_id: 'n72', en: 'To come', es: 'Venir' },
		{ node_id: 'n73', en: 'To eat', es: 'Comer' },
		{ node_id: 'n74', en: 'To drink', es: 'Beber' },
		{ node_id: 'n75', en: 'To sleep', es: 'Dormir' },
		{ node_id: 'n76', en: 'To work', es: 'Trabajar' },
		{ node_id: 'n77', en: 'To study', es: 'Estudiar' },
		{ node_id: 'n78', en: 'To live', es: 'Vivir' },
		{ node_id: 'n79', en: 'To run', es: 'Correr' },
		{ node_id: 'n80', en: 'To write', es: 'Escribir' },
		{ node_id: 'n81', en: 'To read', es: 'Leer' },
		{ node_id: 'n82', en: 'To speak', es: 'Hablar' },
		{ node_id: 'n83', en: 'To listen', es: 'Escuchar' },
		{ node_id: 'n84', en: 'Apple', es: 'Manzana' },
		{ node_id: 'n85', en: 'Banana', es: 'Plátano' },
		{ node_id: 'n86', en: 'Bread', es: 'Pan' },
		{ node_id: 'n87', en: 'Water', es: 'Agua' },
		{ node_id: 'n88', en: 'Milk', es: 'Leche' },
		{ node_id: 'n89', en: 'Coffee', es: 'Café' },
		{ node_id: 'n90', en: 'Tea', es: 'Té' },
		{ node_id: 'n91', en: 'Chicken', es: 'Pollo' },
		{ node_id: 'n92', en: 'Fish', es: 'Pescado' },
		{ node_id: 'n93', en: 'Rice', es: 'Arroz' },
		{ node_id: 'n94', en: 'Beef', es: 'Carne de res' },
		{ node_id: 'n95', en: 'Pork', es: 'Cerdo' },
		{ node_id: 'n96', en: 'Cheese', es: 'Queso' },
		{ node_id: 'n97', en: 'Egg', es: 'Huevo' },
		{ node_id: 'n98', en: 'Vegetable', es: 'Verdura' },
		{ node_id: 'n99', en: 'Fruit', es: 'Fruta' },
		{ node_id: 'n100', en: 'Mother', es: 'Madre' },
		{ node_id: 'n101', en: 'Father', es: 'Padre' },
		{ node_id: 'n102', en: 'Brother', es: 'Hermano' },
		{ node_id: 'n103', en: 'Sister', es: 'Hermana' },
		{ node_id: 'n104', en: 'Son', es: 'Hijo' },
		{ node_id: 'n105', en: 'Daughter', es: 'Hija' },
		{ node_id: 'n106', en: 'Grandfather', es: 'Abuelo' },
		{ node_id: 'n107', en: 'Grandmother', es: 'Abuela' },
		{ node_id: 'n108', en: 'Uncle', es: 'Tío' },
		{ node_id: 'n109', en: 'Aunt', es: 'Tía' },
		{ node_id: 'n110', en: 'Cousin', es: 'Primo/Prima' },
		{ node_id: 'n111', en: 'Sun', es: 'Sol' },
		{ node_id: 'n112', en: 'Rain', es: 'Lluvia' },
		{ node_id: 'n113', en: 'Snow', es: 'Nieve' },
		{ node_id: 'n114', en: 'Wind', es: 'Viento' },
		{ node_id: 'n115', en: 'Cloud', es: 'Nube' },
		{ node_id: 'n116', en: 'Storm', es: 'Tormenta' },
		{ node_id: 'n117', en: 'Hot', es: 'Calor' },
		{ node_id: 'n118', en: 'Cold', es: 'Frío' },
		{ node_id: 'n119', en: 'Warm', es: 'Tibio' },
		{ node_id: 'n120', en: 'Cool', es: 'Fresco' },
		{ node_id: 'n121', en: 'Fog', es: 'Niebla' },
		{ node_id: 'n122', en: 'Thunder', es: 'Trueno' },
		{ node_id: 'n123', en: 'Lightning', es: 'Relámpago' },
		{ node_id: 'n124', en: 'Computer', es: 'Computadora' },
		{ node_id: 'n125', en: 'Internet', es: 'Internet' },
		{ node_id: 'n126', en: 'Phone', es: 'Teléfono' },
		{ node_id: 'n127', en: 'Email', es: 'Correo electrónico' },
		{ node_id: 'n128', en: 'Website', es: 'Sitio web' },
		{ node_id: 'n129', en: 'Software', es: 'Software' },
		{ node_id: 'n130', en: 'Hardware', es: 'Hardware' },
		{ node_id: 'n131', en: 'Application', es: 'Aplicación' },
		{ node_id: 'n132', en: 'Database', es: 'Base de datos' },
		{ node_id: 'n133', en: 'Network', es: 'Red' },
		{ node_id: 'n134', en: 'Server', es: 'Servidor' },
		{ node_id: 'n135', en: "It's raining cats and dogs", es: 'Está lloviendo a cántaros' },
		{ node_id: 'n136', en: 'Break a leg', es: 'Mucha mierda' },
		{ node_id: 'n137', en: 'Piece of cake', es: 'Pan comido' },
		{ node_id: 'n138', en: 'Hit the nail on the head', es: 'Dar en el clavo' },
		{ node_id: 'n139', en: 'Let the cat out of the bag', es: 'Destapar la olla' },
		{ node_id: 'n140', en: 'Cost an arm and a leg', es: 'Costar un ojo de la cara' },
		{ node_id: 'n141', en: 'Bite the bullet', es: 'Apretar los dientes' },
		{ node_id: 'n142', en: 'Burn the midnight oil', es: 'Quemarse las cejas' },
		{ node_id: 'n143', en: 'Jump on the bandwagon', es: 'Subirse al carro' },
		{ node_id: 'n144', en: 'Miss the boat', es: 'Perder el tren' },
		{ node_id: 'n145', en: 'Wake up', es: 'Despertarse' },
		{ node_id: 'n146', en: 'Brush teeth', es: 'Cepillarse los dientes' },
		{ node_id: 'n147', en: 'Take a shower', es: 'Ducharse' },
		{ node_id: 'n148', en: 'Get dressed', es: 'Vestirse' },
		{ node_id: 'n149', en: 'Have breakfast', es: 'Desayunar' },
		{ node_id: 'n150', en: 'Go to work', es: 'Ir al trabajo' },
		{ node_id: 'n151', en: 'Have lunch', es: 'Almorzar' },
		{ node_id: 'n152', en: 'Go home', es: 'Ir a casa' },
		{ node_id: 'n153', en: 'Have dinner', es: 'Cenar' },
		{ node_id: 'n154', en: 'Go to bed', es: 'Ir a la cama' },
		{ node_id: 'n155', en: 'Airport', es: 'Aeropuerto' },
		{ node_id: 'n156', en: 'Hotel', es: 'Hotel' },
		{ node_id: 'n157', en: 'Ticket', es: 'Boleto' },
		{ node_id: 'n158', en: 'Passport', es: 'Pasaporte' },
		{ node_id: 'n159', en: 'Luggage', es: 'Equipaje' },
		{ node_id: 'n160', en: 'Taxi', es: 'Taxi' },
		{ node_id: 'n161', en: 'Train', es: 'Tren' },
		{ node_id: 'n162', en: 'Bus', es: 'Autobús' },
		{ node_id: 'n163', en: 'Map', es: 'Mapa' },
		{ node_id: 'n164', en: 'Tourist', es: 'Turista' },
		{ node_id: 'n165', en: 'Happy', es: 'Feliz' },
		{ node_id: 'n166', en: 'Sad', es: 'Triste' },
		{ node_id: 'n167', en: 'Angry', es: 'Enojado' },
		{ node_id: 'n168', en: 'Surprised', es: 'Sorprendido' },
		{ node_id: 'n169', en: 'Afraid', es: 'Asustado' },
		{ node_id: 'n170', en: 'Excited', es: 'Emocionado' },
		{ node_id: 'n171', en: 'Bored', es: 'Aburrido' },
		{ node_id: 'n172', en: 'Tired', es: 'Cansado' },
		{ node_id: 'n173', en: 'Nervous', es: 'Nervioso' },
		{ node_id: 'n174', en: 'Relaxed', es: 'Relajado' },
		{ node_id: 'n175', en: 'First', es: 'Primero' },
		{ node_id: 'n176', en: 'Second', es: 'Segundo' },
		{ node_id: 'n177', en: 'Third', es: 'Tercero' },
		{ node_id: 'n178', en: 'Fourth', es: 'Cuarto' },
		{ node_id: 'n179', en: 'Fifth', es: 'Quinto' },
		{ node_id: 'n180', en: 'Sixth', es: 'Sexto' },
		{ node_id: 'n181', en: 'Seventh', es: 'Séptimo' },
		{ node_id: 'n182', en: 'Eighth', es: 'Octavo' },
		{ node_id: 'n183', en: 'Ninth', es: 'Noveno' },
		{ node_id: 'n184', en: 'Tenth', es: 'Décimo' },
		{ node_id: 'n185', en: 'How are you?', es: '¿Cómo estás?' },
		{ node_id: 'n186', en: 'What is your name?', es: '¿Cómo te llamas?' },
		{ node_id: 'n187', en: 'My name is...', es: 'Me llamo...' },
		{ node_id: 'n188', en: 'Where are you from?', es: '¿De dónde eres?' },
		{ node_id: 'n189', en: 'I am from...', es: 'Soy de...' },
		{ node_id: 'n190', en: 'How old are you?', es: '¿Cuántos años tienes?' },
		{ node_id: 'n191', en: 'I am ... years old', es: 'Tengo ... años' },
		{ node_id: 'n192', en: 'What do you do?', es: '¿A qué te dedicas?' },
		{ node_id: 'n193', en: 'I am a student', es: 'Soy estudiante' },
		{ node_id: 'n194', en: 'I am a teacher', es: 'Soy profesor' },
		{ node_id: 'n195', en: 'The quick brown fox jumps over the lazy dog', es: 'El rápido zorro marrón salta sobre el perro perezoso' },
		{ node_id: 'n196', en: 'She sells seashells by the seashore', es: 'Ella vende conchas marinas a la orilla del mar' },
		{ node_id: 'n197', en: 'How much wood would a woodchuck chuck?', es: '¿Cuánta madera roería un roedor?' },
		{ node_id: 'n198', en: 'Artificial Intelligence', es: 'Inteligencia Artificial' },
		{ node_id: 'n199', en: 'Machine Learning', es: 'Aprendizaje Automático' },
		{ node_id: 'n200', en: 'Deep Learning', es: 'Aprendizaje Profundo' },
		{ node_id: 'n201', en: 'Neural Network', es: 'Red Neuronal' },
		{ node_id: 'n202', en: 'Big Data', es: 'Grandes Datos' },
		{ node_id: 'n203', en: 'Cloud Computing', es: 'Computación en la Nube' },
		{ node_id: 'n204', en: 'Internet of Things', es: 'Internet de las Cosas' },
		{ node_id: 'n205', en: 'Cybersecurity', es: 'Ciberseguridad' },
		{ node_id: 'n206', en: 'Blockchain', es: 'Cadena de Bloques' },
		{ node_id: 'n207', en: 'Virtual Reality', es: 'Realidad Virtual' },
		{ node_id: 'n208', en: 'The car is fast', es: 'El coche es rápido' },
		{ node_id: 'n209', en: 'The house is big', es: 'La casa es grande' },
		{ node_id: 'n210', en: 'The book is interesting', es: 'El libro es interesante' },
		{ node_id: 'n211', en: 'The movie is boring', es: 'La película es aburrida' },
		{ node_id: 'n212', en: 'The food is delicious', es: 'La comida es deliciosa' },
		{ node_id: 'n213', en: 'The dog is friendly', es: 'El perro es amistoso' },
		{ node_id: 'n214', en: 'The sky is clear', es: 'El cielo está despejado' },
		{ node_id: 'n215', en: 'The room is clean', es: 'La habitación está limpia' },
		{ node_id: 'n216', en: 'What is this?', es: '¿Qué es esto?' },
		{ node_id: 'n217', en: 'Where is the bathroom?', es: '¿Dónde está el baño?' },
		{ node_id: 'n218', en: 'How much does it cost?', es: '¿Cuánto cuesta?' },
		{ node_id: 'n219', en: 'Can you help me?', es: '¿Me puedes ayudar?' },
		{ node_id: 'n220', en: 'Do you speak English?', es: '¿Hablas inglés?' },
		{ node_id: 'n221', en: 'Turn left', es: 'Gira a la izquierda' },
		{ node_id: 'n222', en: 'Turn right', es: 'Gira a la derecha' },
		{ node_id: 'n223', en: 'Go straight', es: 'Sigue recto' },
		{ node_id: 'n224', en: 'Stop here', es: 'Para aquí' },
		{ node_id: 'n225', en: "It's on the left", es: 'Está a la izquierda' },
		{ node_id: 'n226', en: "It's on the right", es: 'Está a la derecha' },
		{ node_id: 'n227', en: "It's straight ahead", es: 'Está derecho adelante' },
		{ node_id: 'n228', en: "It's behind you", es: 'Está detrás de ti' },
		{ node_id: 'n229', en: "It's next to the bank", es: 'Está al lado del banco' },
		{ node_id: 'n230', en: "It's across from the park", es: 'Está enfrente del parque' },
		{ node_id: 'n231', en: 'Kill two birds with one stone', es: 'Matar dos pájaros de un tiro' },
		{ node_id: 'n232', en: 'The early bird catches the worm', es: 'A quien madruga, Dios le ayuda' },
		{ node_id: 'n233', en: "Don't count your chickens before they hatch", es: 'No vendas la piel del oso antes de cazarlo' },
		{ node_id: 'n234', en: 'Every cloud has a silver lining', es: 'No hay mal que por bien no venga' },
		{ node_id: 'n235', en: 'When in Rome, do as the Romans do', es: 'Donde fueres, haz lo que vieres' },
		{ node_id: 'n236', en: 'Please find attached', es: 'Adjunto encontrará' },
		{ node_id: 'n237', en: 'As per your request', es: 'Según su solicitud' },
		{ node_id: 'n238', en: 'I look forward to hearing from you', es: 'Espero su respuesta' },
		{ node_id: 'n239', en: 'Thank you for your time', es: 'Gracias por su tiempo' },
		{ node_id: 'n240', en: 'Best regards', es: 'Saludos cordiales' },
		{ node_id: 'n241', en: 'I need a doctor', es: 'Necesito un médico' },
		{ node_id: 'n242', en: 'Call an ambulance', es: 'Llama a una ambulancia' },
		{ node_id: 'n243', en: 'I have a headache', es: 'Tengo dolor de cabeza' },
		{ node_id: 'n244', en: 'I feel sick', es: 'Me siento mal' },
		{ node_id: 'n245', en: 'Where is the hospital?', es: '¿Dónde está el hospital?' },
		{ node_id: 'n246', en: 'Cat', es: 'Gato' },
		{ node_id: 'n247', en: 'Dog', es: 'Perro' },
		{ node_id: 'n248', en: 'Bird', es: 'Pájaro' },
		{ node_id: 'n249', en: 'Fish', es: 'Pez' },
		{ node_id: 'n250', en: 'Horse', es: 'Caballo' },
		{ node_id: 'n251', en: 'Cow', es: 'Vaca' },
		{ node_id: 'n252', en: 'Sheep', es: 'Oveja' },
		{ node_id: 'n253', en: 'Pig', es: 'Cerdo' },
		{ node_id: 'n254', en: 'Chicken', es: 'Gallina' },
		{ node_id: 'n255', en: 'Rabbit', es: 'Conejo' },
		{ node_id: 'n256', en: 'Teacher', es: 'Profesor' },
		{ node_id: 'n257', en: 'Doctor', es: 'Médico' },
		{ node_id: 'n258', en: 'Engineer', es: 'Ingeniero' },
		{ node_id: 'n259', en: 'Nurse', es: 'Enfermera' },
		{ node_id: 'n260', en: 'Lawyer', es: 'Abogado' },
		{ node_id: 'n261', en: 'Chef', es: 'Cocinero' },
		{ node_id: 'n262', en: 'Driver', es: 'Conductor' },
		{ node_id: 'n263', en: 'Artist', es: 'Artista' },
		{ node_id: 'n264', en: 'Musician', es: 'Músico' },
		{ node_id: 'n265', en: 'Writer', es: 'Escritor' },
		{ node_id: 'n266', en: 'Table', es: 'Mesa' },
		{ node_id: 'n267', en: 'Chair', es: 'Silla' },
		{ node_id: 'n268', en: 'Bed', es: 'Cama' },
		{ node_id: 'n269', en: 'Sofa', es: 'Sofá' },
		{ node_id: 'n270', en: 'Lamp', es: 'Lámpara' },
		{ node_id: 'n271', en: 'Mirror', es: 'Espejo' },
		{ node_id: 'n272', en: 'Clock', es: 'Reloj' },
		{ node_id: 'n273', en: 'Door', es: 'Puerta' },
		{ node_id: 'n274', en: 'Window', es: 'Ventana' },
		{ node_id: 'n275', en: 'Television', es: 'Televisión' },
		{ node_id: 'n276', en: 'Car', es: 'Coche' },
		{ node_id: 'n277', en: 'Bicycle', es: 'Bicicleta' },
		{ node_id: 'n278', en: 'Motorcycle', es: 'Motocicleta' },
		{ node_id: 'n279', en: 'Boat', es: 'Barco' },
		{ node_id: 'n280', en: 'Airplane', es: 'Avión' },
		{ node_id: 'n281', en: 'Road', es: 'Carretera' },
		{ node_id: 'n282', en: 'Bridge', es: 'Puente' },
		{ node_id: 'n283', en: 'Street', es: 'Calle' },
		{ node_id: 'n284', en: 'City', es: 'Ciudad' },
		{ node_id: 'n285', en: 'Village', es: 'Pueblo' },
		{ node_id: 'n286', en: 'Mountain', es: 'Montaña' },
		{ node_id: 'n287', en: 'River', es: 'Río' },
		{ node_id: 'n288', en: 'Lake', es: 'Lago' },
		{ node_id: 'n289', en: 'Forest', es: 'Bosque' },
		{ node_id: 'n290', en: 'Beach', es: 'Playa' },
		{ node_id: 'n291', en: 'Morning', es: 'Mañana' },
		{ node_id: 'n292', en: 'Afternoon', es: 'Tarde' },
		{ node_id: 'n293', en: 'Evening', es: 'Noche' },
		{ node_id: 'n294', en: 'Night', es: 'Noche' },
		{ node_id: 'n295', en: 'Day', es: 'Día' },
		{ node_id: 'n296', en: 'Week', es: 'Semana' },
		{ node_id: 'n297', en: 'Month', es: 'Mes' },
		{ node_id: 'n298', en: 'Year', es: 'Año' },
		{ node_id: 'n299', en: 'Hour', es: 'Hora' },
		{ node_id: 'n300', en: 'Minute', es: 'Minuto' },
		{ node_id: 'n301', en: 'Yes', es: 'Sí' },
		{ node_id: 'n302', en: 'No', es: 'No' },
		{ node_id: 'n303', en: 'Maybe', es: 'Tal vez' },
		{ node_id: 'n304', en: 'Always', es: 'Siempre' },
		{ node_id: 'n305', en: 'Never', es: 'Nunca' },
		{ node_id: 'n306', en: 'Sometimes', es: 'A veces' },
		{ node_id: 'n307', en: 'Now', es: 'Ahora' },
		{ node_id: 'n308', en: 'Later', es: 'Más tarde' },
		{ node_id: 'n309', en: 'Soon', es: 'Pronto' },
		{ node_id: 'n310', en: 'Yesterday', es: 'Ayer' },
		{ node_id: 'n311', en: 'Today', es: 'Hoy' },
		{ node_id: 'n312', en: 'Tomorrow', es: 'Mañana' },
		{ node_id: 'n313', en: 'Big', es: 'Grande' },
		{ node_id: 'n314', en: 'Small', es: 'Pequeño' },
		{ node_id: 'n315', en: 'Long', es: 'Largo' },
		{ node_id: 'n316', en: 'Short', es: 'Corto' },
		{ node_id: 'n317', en: 'Tall', es: 'Alto' },
		{ node_id: 'n318', en: 'Low', es: 'Bajo' },
		{ node_id: 'n319', en: 'Fast', es: 'Rápido' },
		{ node_id: 'n320', en: 'Slow', es: 'Lento' },
		{ node_id: 'n321', en: 'Beautiful', es: 'Hermoso' },
		{ node_id: 'n322', en: 'Ugly', es: 'Feo' },
		{ node_id: 'n323', en: 'Good', es: 'Bueno' },
		{ node_id: 'n324', en: 'Bad', es: 'Malo' },
		{ node_id: 'n325', en: 'New', es: 'Nuevo' },
		{ node_id: 'n326', en: 'Old', es: 'Viejo' },
		{ node_id: 'n327', en: 'I like to read books', es: 'Me gusta leer libros' },
		{ node_id: 'n328', en: 'She runs every morning', es: 'Ella corre todas las mañanas' },
		{ node_id: 'n329', en: 'We are going to the park', es: 'Vamos al parque' },
		{ node_id: 'n330', en: 'They play soccer on weekends', es: 'Ellos juegan fútbol los fines de semana' },
		{ node_id: 'n331', en: 'He writes music', es: 'Él escribe música' },
		{ node_id: 'n332', en: 'The cat sleeps on the sofa', es: 'El gato duerme en el sofá' },
		{ node_id: 'n333', en: 'I need more time', es: 'Necesito más tiempo' },
		{ node_id: 'n334', en: 'She is very happy today', es: 'Ella está muy feliz hoy' },
		{ node_id: 'n335', en: 'We live in a small house', es: 'Vivimos en una casa pequeña' },
		{ node_id: 'n336', en: 'They want to travel', es: 'Ellos quieren viajar' },
		{ node_id: 'n337', en: 'Book', es: 'Libro' },
		{ node_id: 'n338', en: 'Pen', es: 'Pluma' },
		{ node_id: 'n339', en: 'Pencil', es: 'Lápiz' },
		{ node_id: 'n340', en: 'Paper', es: 'Papel' },
		{ node_id: 'n341', en: 'Notebook', es: 'Cuaderno' },
		{ node_id: 'n342', en: 'Bag', es: 'Bolso' },
		{ node_id: 'n343', en: 'School', es: 'Escuela' },
		{ node_id: 'n344', en: 'Classroom', es: 'Aula' },
		{ node_id: 'n345', en: 'Desk', es: 'Escritorio' },
		{ node_id: 'n346', en: 'Chair', es: 'Silla' },
		{ node_id: 'n347', en: 'Friend', es: 'Amigo' },
		{ node_id: 'n348', en: 'Love', es: 'Amor' },
		{ node_id: 'n349', en: 'Peace', es: 'Paz' },
		{ node_id: 'n350', en: 'Hope', es: 'Esperanza' },
		{ node_id: 'n351', en: 'Dream', es: 'Sueño' },
		{ node_id: 'n352', en: 'Life', es: 'Vida' },
		{ node_id: 'n353', en: 'Work', es: 'Trabajo' },
		{ node_id: 'n354', en: 'Home', es: 'Hogar' },
		{ node_id: 'n355', en: 'Family', es: 'Familia' },
		{ node_id: 'n356', en: 'Time', es: 'Tiempo' },
		{ node_id: 'n357', en: 'Money', es: 'Dinero' },
		{ node_id: 'n358', en: 'Store', es: 'Tienda' },
		{ node_id: 'n359', en: 'Market', es: 'Mercado' },
		{ node_id: 'n360', en: 'Restaurant', es: 'Restaurante' },
		{ node_id: 'n361', en: 'Menu', es: 'Menú' },
		{ node_id: 'n362', en: 'Waiter', es: 'Camarero' },
		{ node_id: 'n363', en: 'Bill', es: 'Cuenta' },
		{ node_id: 'n364', en: 'Tip', es: 'Propina' },
		{ node_id: 'n365', en: 'Table', es: 'Mesa' },
		{ node_id: 'n366', en: 'Glass', es: 'Vaso' },
		{ node_id: 'n367', en: 'Plate', es: 'Plato' },
		{ node_id: 'n368', en: 'Fork', es: 'Tenedor' },
		{ node_id: 'n369', en: 'Knife', es: 'Cuchillo' },
		{ node_id: 'n370', en: 'Spoon', es: 'Cuchara' },
		{ node_id: 'n371', en: 'Summer', es: 'Verano' },
		{ node_id: 'n372', en: 'Winter', es: 'Invierno' },
		{ node_id: 'n373', en: 'Spring', es: 'Primavera' },
		{ node_id: 'n374', en: 'Fall', es: 'Otoño' },
		{ node_id: 'n375', en: 'Sunrise', es: 'Amanecer' },
		{ node_id: 'n376', en: 'Sunset', es: 'Atardecer' },
		{ node_id: 'n377', en: 'Moon', es: 'Luna' },
		{ node_id: 'n378', en: 'Star', es: 'Estrella' },
		{ node_id: 'n379', en: 'Sky', es: 'Cielo' },
		{ node_id: 'n380', en: 'Earth', es: 'Tierra' },
		{ node_id: 'n381', en: 'Flower', es: 'Flor' },
		{ node_id: 'n382', en: 'Tree', es: 'Árbol' },
		{ node_id: 'n383', en: 'Grass', es: 'Hierba' },
		{ node_id: 'n384', en: 'Leaf', es: 'Hoja' },
		{ node_id: 'n385', en: 'Plant', es: 'Planta' },
		{ node_id: 'n386', en: 'Garden', es: 'Jardín' },
		{ node_id: 'n387', en: 'Park', es: 'Parque' },
		{ node_id: 'n388', en: 'Path', es: 'Camino' },
		{ node_id: 'n389', en: 'Hill', es: 'Colina' },
		{ node_id: 'n390', en: 'Valley', es: 'Valle' },
		{ node_id: 'n391', en: 'Game', es: 'Juego' },
		{ node_id: 'n392', en: 'Sport', es: 'Deporte' },
		{ node_id: 'n393', en: 'Ball', es: 'Pelota' },
		{ node_id: 'n394', en: 'Team', es: 'Equipo' },
		{ node_id: 'n395', en: 'Player', es: 'Jugador' },
		{ node_id: 'n396', en: 'Goal', es: 'Gol' },
		{ node_id: 'n397', en: 'Score', es: 'Puntuación' },
		{ node_id: 'n398', en: 'Win', es: 'Ganar' },
		{ node_id: 'n399', en: 'Lose', es: 'Perder' },
		{ node_id: 'n400', en: 'Play', es: 'Jugar' },
		{ node_id: 'n401', en: 'Song', es: 'Canción' },
		{ node_id: 'n402', en: 'Dance', es: 'Baile' },
		{ node_id: 'n403', en: 'Movie', es: 'Película' },
		{ node_id: 'n404', en: 'Show', es: 'Espectáculo' },
		{ node_id: 'n405', en: 'Art', es: 'Arte' },
		{ node_id: 'n406', en: 'Painting', es: 'Pintura' },
		{ node_id: 'n407', en: 'Photo', es: 'Foto' },
		{ node_id: 'n408', en: 'Camera', es: 'Cámara' },
		{ node_id: 'n409', en: 'Picture', es: 'Imagen' },
		{ node_id: 'n410', en: 'Music', es: 'Música' },
		{ node_id: 'n411', en: 'Shirt', es: 'Camisa' },
		{ node_id: 'n412', en: 'Pants', es: 'Pantalones' },
		{ node_id: 'n413', en: 'Shoes', es: 'Zapatos' },
		{ node_id: 'n414', en: 'Hat', es: 'Sombrero' },
		{ node_id: 'n415', en: 'Jacket', es: 'Chaqueta' },
		{ node_id: 'n416', en: 'Dress', es: 'Vestido' },
		{ node_id: 'n417', en: 'Skirt', es: 'Falda' },
		{ node_id: 'n418', en: 'Socks', es: 'Calcetines' },
		{ node_id: 'n419', en: 'Belt', es: 'Cinturón' },
		{ node_id: 'n420', en: 'Gloves', es: 'Guantes' },
		{ node_id: 'n421', en: 'Head', es: 'Cabeza' },
		{ node_id: 'n422', en: 'Face', es: 'Cara' },
		{ node_id: 'n423', en: 'Eye', es: 'Ojo' },
		{ node_id: 'n424', en: 'Ear', es: 'Oído' },
		{ node_id: 'n425', en: 'Nose', es: 'Nariz' },
		{ node_id: 'n426', en: 'Mouth', es: 'Boca' },
		{ node_id: 'n427', en: 'Hand', es: 'Mano' },
		{ node_id: 'n428', en: 'Arm', es: 'Brazo' },
		{ node_id: 'n429', en: 'Leg', es: 'Pierna' },
		{ node_id: 'n430', en: 'Foot', es: 'Pie' },
		{ node_id: 'n431', en: 'I want to go home', es: 'Quiero ir a casa' },
		{ node_id: 'n432', en: 'She likes to cook', es: 'A ella le gusta cocinar' },
		{ node_id: 'n433', en: 'We need more water', es: 'Necesitamos más agua' },
		{ node_id: 'n434', en: 'They are playing outside', es: 'Están jugando afuera' },
		{ node_id: 'n435', en: 'He reads the newspaper', es: 'Él lee el periódico' },
		{ node_id: 'n436', en: 'The sun is shining', es: 'El sol está brillando' },
		{ node_id: 'n437', en: 'It’s a beautiful day', es: 'Es un día hermoso' },
		{ node_id: 'n438', en: 'I’m going to the store', es: 'Voy a la tienda' },
		{ node_id: 'n439', en: 'She dances very well', es: 'Ella baila muy bien' },
		{ node_id: 'n440', en: 'We watched a movie', es: 'Vimos una película' },
		{ node_id: 'n441', en: 'Bread is on the table', es: 'El pan está en la mesa' },
		{ node_id: 'n442', en: 'The dog runs fast', es: 'El perro corre rápido' },
		{ node_id: 'n443', en: 'I see the moon', es: 'Veo la luna' },
		{ node_id: 'n444', en: 'She sings a song', es: 'Ella canta una canción' },
		{ node_id: 'n445', en: 'We are very tired', es: 'Estamos muy cansados' },
		{ node_id: 'n446', en: 'He paints the house', es: 'Él pinta la casa' },
		{ node_id: 'n447', en: 'The flower is red', es: 'La flor es roja' },
		{ node_id: 'n448', en: 'I hear the birds', es: 'Oigo los pájaros' },
		{ node_id: 'n449', en: 'They swim in the lake', es: 'Ellos nadan en el lago' },
		{ node_id: 'n450', en: 'The sky is blue', es: 'El cielo es azul' },
		{ node_id: 'n451', en: 'Please close the door', es: 'Por favor, cierra la puerta' },
		{ node_id: 'n452', en: 'Open the window', es: 'Abre la ventana' },
		{ node_id: 'n453', en: 'Turn off the light', es: 'Apaga la luz' },
		{ node_id: 'n454', en: 'Sit down here', es: 'Siéntate aquí' },
		{ node_id: 'n455', en: 'Stand up now', es: 'Levántate ahora' },
		{ node_id: 'n456', en: 'Give me the book', es: 'Dame el libro' },
		{ node_id: 'n457', en: 'Take this pen', es: 'Toma esta pluma' },
		{ node_id: 'n458', en: 'Look at the sky', es: 'Mira el cielo' },
		{ node_id: 'n459', en: 'Listen to the music', es: 'Escucha la música' },
		{ node_id: 'n460', en: 'Wait for me', es: 'Espérame' },
		{ node_id: 'n461', en: 'I don’t understand', es: 'No entiendo' },
		{ node_id: 'n462', en: 'Can you repeat that?', es: '¿Puedes repetir eso?' },
		{ node_id: 'n463', en: 'What time is it?', es: '¿Qué hora es?' },
		{ node_id: 'n464', en: 'It’s ten o’clock', es: 'Son las diez en punto' },
		{ node_id: 'n465', en: 'Where is my phone?', es: '¿Dónde está mi teléfono?' },
		{ node_id: 'n466', en: 'I lost my keys', es: 'Perdí mis llaves' },
		{ node_id: 'n467', en: 'This is my house', es: 'Esta es mi casa' },
		{ node_id: 'n468', en: 'That is your car', es: 'Ese es tu coche' },
		{ node_id: 'n469', en: 'These are my friends', es: 'Estos son mis amigos' },
		{ node_id: 'n470', en: 'Those are her shoes', es: 'Esos son sus zapatos' },
		{ node_id: 'n471', en: 'I have two cats', es: 'Tengo dos gatos' },
		{ node_id: 'n472', en: 'She has a big dog', es: 'Ella tiene un perro grande' },
		{ node_id: 'n473', en: 'We need new chairs', es: 'Necesitamos sillas nuevas' },
		{ node_id: 'n474', en: 'They want more food', es: 'Quieren más comida' },
		{ node_id: 'n475', en: 'He likes fast cars', es: 'Le gustan los coches rápidos' },
		{ node_id: 'n476', en: 'The store is open', es: 'La tienda está abierta' },
		{ node_id: 'n477', en: 'The park is closed', es: 'El parque está cerrado' },
		{ node_id: 'n478', en: 'It’s a sunny day', es: 'Es un día soleado' },
		{ node_id: 'n479', en: 'The rain stopped', es: 'La lluvia paró' },
		{ node_id: 'n480', en: 'The wind is strong', es: 'El viento es fuerte' },
		{ node_id: 'n481', en: 'I’m learning Spanish', es: 'Estoy aprendiendo español' },
		{ node_id: 'n482', en: 'She teaches English', es: 'Ella enseña inglés' },
		{ node_id: 'n483', en: 'We study together', es: 'Estudiamos juntos' },
		{ node_id: 'n484', en: 'They work hard', es: 'Trabajan duro' },
		{ node_id: 'n485', en: 'He plays the guitar', es: 'Toca la guitarra' },
		{ node_id: 'n486', en: 'The baby is sleeping', es: 'El bebé está durmiendo' },
		{ node_id: 'n487', en: 'I’m cooking dinner', es: 'Estoy cocinando la cena' },
		{ node_id: 'n488', en: 'She’s reading a book', es: 'Está leyendo un libro' },
		{ node_id: 'n489', en: 'We’re watching TV', es: 'Estamos viendo televisión' },
		{ node_id: 'n490', en: 'They’re running outside', es: 'Están corriendo afuera' },
		{ node_id: 'n491', en: 'This coffee is hot', es: 'Este café está caliente' },
		{ node_id: 'n492', en: 'That water is cold', es: 'Esa agua está fría' },
		{ node_id: 'n493', en: 'These apples are sweet', es: 'Estas manzanas son dulces' },
		{ node_id: 'n494', en: 'Those chairs are old', es: 'Esas sillas son viejas' },
		{ node_id: 'n495', en: 'I see a big tree', es: 'Veo un árbol grande' },
		{ node_id: 'n496', en: 'She hears a loud noise', es: 'Ella oye un ruido fuerte' },
		{ node_id: 'n497', en: 'We feel very happy', es: 'Nos sentimos muy felices' },
		{ node_id: 'n498', en: 'They know the answer', es: 'Ellos saben la respuesta' },
		{ node_id: 'n499', en: 'He understands me', es: 'Él me entiende' },
		{ node_id: 'n500', en: 'The world is beautiful', es: 'El mundo es hermoso' },
	],
};
